pipeline:
  build:
    when:
      event: [push]
    image: node:14.15-alpine
    commands:
      - git fetch --tags
      - npm ci
      - npm run build

  eslint:
    when:
      event: [push]
    image: node:14.15-alpine
    group: checks
    commands:
      - npm run eslint:check

  prettier:
    when:
      event: [push]
    image: node:14.15-alpine
    group: checks
    commands:
      - npm run prettier:check


  build:
    when:
      event: [push]
    image: node:14.15-alpine
    commands:
      - NODE_ENV=production npm run build

  publish:
    when:
      branch: master
      event: [push]
    image: node:14.15-alpine
    secrets: ['npm_token']
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN
      - npm publish
